{{- if .Values.secrets.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "neobank.fullname" . }}-app
  labels:
    {{- include "neobank.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecrets.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: neobank/database-url
    - secretKey: redis-url
      remoteRef:
        key: neobank/redis-url
    - secretKey: jwt-secret
      remoteRef:
        key: neobank/jwt-secret
    - secretKey: kafka-brokers
      remoteRef:
        key: neobank/kafka-brokers
    - secretKey: ledger-grpc-addr
      remoteRef:
        key: neobank/ledger-grpc-addr
    - secretKey: otel-endpoint
      remoteRef:
        key: neobank/otel-endpoint
    - secretKey: vault-addr
      remoteRef:
        key: neobank/vault-addr
    - secretKey: vault-token
      remoteRef:
        key: neobank/vault-token
    - secretKey: settlement-ledger-account-id
      remoteRef:
        key: neobank/settlement-ledger-account-id
{{- end }}