{{- if .Values.networkPolicy.enabled }}
{{- $fullname := include "neobank.fullname" . -}}
{{- $ns := .Release.Namespace -}}
{{- $ingressNs := .Values.networkPolicy.ingressControllerNamespace -}}
{{- $dnsNs := .Values.networkPolicy.dnsNamespace -}}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-default-deny
  labels:
    {{- include "neobank.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-dns-egress
  labels:
    {{- include "neobank.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $dnsNs }}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-gateway-ingress
  labels:
    {{- include "neobank.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: gateway
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $ingressNs }}
      ports:
        - port: {{ .Values.workloads.gateway.httpPort }}
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-internal-mesh
  labels:
    {{- include "neobank.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
    - ports:
        - port: 5432
          protocol: TCP
        - port: 6379
          protocol: TCP
        - port: 9092
          protocol: TCP
        - port: 8200
          protocol: TCP
        - port: 4317
          protocol: TCP
        - port: 50051
          protocol: TCP
{{- end }}