{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neobank.secretName" . }}
  labels:
    {{- include "neobank.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ required "config.databaseURL is required when secrets.create=true" .Values.config.databaseURL | quote }}
  redis-url: {{ .Values.config.redisURL | quote }}
  jwt-secret: {{ required "config.jwtSecret is required when secrets.create=true" .Values.config.jwtSecret | quote }}
  kafka-brokers: {{ .Values.config.kafkaBrokers | quote }}
  ledger-grpc-addr: {{ .Values.config.ledgerGrpcAddr | quote }}
  otel-endpoint: {{ .Values.config.otelEndpoint | quote }}
  vault-addr: {{ .Values.config.vaultAddr | quote }}
  vault-token: {{ .Values.config.vaultToken | quote }}
  settlement-ledger-account-id: {{ .Values.config.settlementLedgerAccountID | quote }}
{{- end }}