{{- if and .Values.goledger.enabled .Values.goledger.postgres.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.goledger.postgresCluster" . }}-app
  namespace: {{ include "platform.namespace" . }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    cnpg.io/cluster: {{ include "platform.goledger.postgresCluster" . }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.goledger.postgres.owner | quote }}
  password: {{ .Values.goledger.postgres.password | quote }}
{{- end }}