apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: neobank-app
  namespace: neobank
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-neobank
    kind: ClusterSecretStore
  target:
    name: neobank-app
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: neobank/database-url
        property: value
    - secretKey: redis-url
      remoteRef:
        key: neobank/redis-url
        property: value
    - secretKey: jwt-secret
      remoteRef:
        key: neobank/jwt-secret
        property: value
    - secretKey: kafka-brokers
      remoteRef:
        key: neobank/kafka-brokers
        property: value
    - secretKey: ledger-grpc-addr
      remoteRef:
        key: neobank/ledger-grpc-addr
        property: value
    - secretKey: otel-endpoint
      remoteRef:
        key: neobank/otel-endpoint
        property: value
    - secretKey: vault-addr
      remoteRef:
        key: neobank/vault-addr
        property: value
    - secretKey: settlement-ledger-account-id
      remoteRef:
        key: neobank/settlement-ledger-account-id
        property: value