apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: neobank
  sources:
    - repoURL: https://charts.redpanda.com
      chart: redpanda
      targetRevision: 5.9.0
      helm:
        valueFiles:
          - $values/deploy/platform/redpanda-values.yaml
        parameters:
          - name: fullnameOverride
            value: redpanda
    - repoURL: https://github.com/iho/neobank.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: neobank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m